### ISSUE TITLE
Multiple attributes with the same name result in serialization issues

### ISSUE THREAD

**Issue by kylemc** [Microsoft/bond#129]
Adding multiple attributes with the same name will cause serialization failures that are difficult to debug. It's unclear from the documentation that multiple AttributeAttributes are not supported.

The following schema fails to serialize

```
struct TitleIdentity
{
    // Gets or sets the value of the title id
    [Claim("http://schemas.microsoft.com/xbox/2011/07/claims/title/id")]
    [Claim("http://schemas.microsoft.com/xbox/2011/07/claims/title/receipt/id")]
    0: nullable<uint32> Id;
}
```

with the following exception

```
Result StackTrace:	
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Bond.Schema`1.Cache.GetAttributes(MemberInfo memberInfo)
   at Bond.Schema`1.Cache.<GetFields>b__8(ISchemaField field)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Bond.Schema`1.Cache.GetFields(Type type)
   at Bond.Schema`1.Cache..ctor(Type type)
   at Bond.Schema`1..cctor()
 --- End of inner exception stack trace ---
    at Bond.Schema`1.get_Metadata()
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Bond.Schema`1.Cache.GetTypeDef(Type type)
   at Bond.Schema`1.Cache.GetTypeDef(Type type)
   at Bond.Schema`1.Cache.GetStructDef(Type type, Metadata metadata, Metadata[] fields)
   at Bond.Schema`1.Cache..ctor(Type type)
   at Bond.Schema`1..cctor()
 --- End of inner exception stack trace ---
    at Bond.Schema`1.get_Metadata()
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Bond.Schema`1.Cache.GetTypeDef(Type type)
   at Bond.Schema`1.Cache.GetTypeDef(Type type)
   at Bond.Schema`1.Cache.GetTypeDef(Type type)
   at Bond.Schema`1.Cache.GetStructDef(Type type, Metadata metadata, Metadata[] fields)
   at Bond.Schema`1.Cache..ctor(Type type)
   at Bond.Schema`1..cctor()
 --- End of inner exception stack trace ---
    at Bond.Schema`1.get_Metadata()
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Bond.Schema`1.Cache.GetTypeDef(Type type)
   at Bond.Schema`1.Cache.GetStructDef(Type type, Metadata metadata, Metadata[] fields)
   at Bond.Schema`1.Cache..ctor(Type type)
   at Bond.Schema`1..cctor()
 --- End of inner exception stack trace ---
    at Bond.Schema`1.get_RuntimeSchema()
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Bond.Schema.GetRuntimeSchema(Type type)
   at lambda_method(Closure , Expression`1 , Type )
   at Bond.Expressions.SerializerGeneratorFactory`2.Create[S](Expression`1 deferredSerialize, S schema)
   at Bond.Serializer`1..ctor(Type type)
   at Bond.Serialize.Cache`2..cctor()
 --- End of inner exception stack trace ---
    at Bond.Serialize.To[W,T](W writer, T obj)
...

Result Message:	
...
System.TypeInitializationException: The type initializer for 'Cache`2' threw an exception. --->
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
 System.TypeInitializationException: The type initializer for 'Bond.Schema`1' threw an exception. --->
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
 System.TypeInitializationException: The type initializer for 'Bond.Schema`1' threw an exception. --->
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
 System.TypeInitializationException: The type initializer for 'Bond.Schema`1' threw an exception. --->
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
 System.TypeInitializationException: The type initializer for 'Bond.Schema`1' threw an exception. --->
 System.ArgumentException: An item with the same key has already been added.
```

**Comment by lalo** [comment]
We need a better error message here:
https://github.com/Microsoft/bond/blob/6c11df8eb7fc1bb7aeaab47ad89ac72f2ff26861/cs/src/core/Schema.cs#L238

or

decide on chaining attributes with the same key under the same string value with ',' or ';'
