### ISSUE TITLE
Cannot serialize required binary guid using version 7 (C#)

### ISSUE THREAD

**Issue by nrandell** [Microsoft/bond#660]
I just upgraded to the latest libraries and some of my unit tests started failing around the serialization of Guid to array segments. 

I took the guid example, cloned it to (https://github.com/nrandell/bond-guid.git) and extended to have record with required and one without. The one without required works fine, the other throws a TypeInitializationException

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Cache`2' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: variable 'convertedBlob' of type 'System.ArraySegment`1[System.Byte]' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Bond.Serializer`1.SerializerHelper..ctor(ObjectParser parser, Type type, Boolean inlineNested) in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\Serializer.cs:line 140
   at Bond.Serializer`1.TwoPassSerializerHelper`1..ctor(ObjectParser parser, Type type, Boolean inlineNested)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Bond.Serializer`1..ctor(Type type, IParser parser, Boolean inlineNested) in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\Serializer.cs:line 117
   at Bond.Serialize.Cache`2..cctor() in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\Serializer.cs:line 21
   --- End of inner exception stack trace ---
   at Bond.Serialize.To[W,T](W writer, T obj) in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\Serializer.cs:line 33
   at BondGuid.Program.TestExampleRequired() in C:\Users\nick\Source\playground\BondGuid\BondGuid\Program.cs:line 105
   at BondGuid.Program.Main() in C:\Users\nick\Source\playground\BondGuid\BondGuid\Program.cs:line 70
```

**Comment by chwarr** [comment]
Thanks for the report. It's likely that commit https://github.com/Microsoft/bond/commit/64f63dfe779b7339e79ffb7308d007f105df702f introduced this regression. We're looking into this now.

**Comment by nrandell** [comment]
Nice quick work @chwarr  and @lalo - any idea when this will make it's way to nuget?

**Comment by lalo** [comment]
@nrandell the nuget is live you can update now to 7.0.1
