### ISSUE TITLE
Serialization fails is some cases when there are multiple type aliases

### ISSUE THREAD

**Issue by kylemc** [Microsoft/bond#68]
*[Update]
I got codegen and samples working with two --using="type-alias=generated-code-type" statements in the options. Unfortunately, serialization still fails with the exception below.*

I'm trying to author an IDL with multiple aliases. The IDL parses fine, but the compiler doesn't seem to account for more than one kvp in the --using parameter.

Expected:
  --using="datetime=System.DateTime;guid=System.Guid" works

    [global::Bond.Id(2), global::Bond.Type(typeof(ulong)), global::Bond.Required]
    public System.DateTime timestampUtc { get; set; }

Actual:
  --using="datetime=System.DateTime;guid=System.Guid"

results in generated code like the following:

    [global::Bond.Id(2), global::Bond.Type(typeof(ulong)), global::Bond.Required]
    public System.DateTime,guid=System.Guid timestampUtc { get; set; }

**Comment by kylemc** [comment]
Something like this possibly?
  mapM Just (splitOn ";" "asdf;asdf")

**Comment by kylemc** [comment]
One of the workarounds I tried was multiple --using options, but it resulted in the following exception which pointed to a bad join on aliased types and made me think that only the single option was being read.

>    System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'Cache`2' threw an exception.
  Source=Bond
  TypeName=Cache`2
  StackTrace:
       at Bond.Serialize.To[W,T](W writer, T obj)
       at Bond.Bonded`1.Bond.IBonded.Serialize[W](W writer)
       at lambda_method(Closure , Object , CompactBinaryWriter`1 )
       at Bond.Serializer`1.Serialize(Object obj, W writer)
       at Bond.Serialize.To[W,T](W writer, T obj)
  InnerException: System.ArgumentNullException
       HResult=-2147467261
       Message=Value cannot be null.
Parameter name: field
       Source=System.Core
       ParamName=field
       StackTrace:
            at System.Linq.Expressions.Expression.Field(Expression expression, FieldInfo field)
            at Bond.Expressions.DataExpression.PropertyOrField(Expression expression, String name)
            at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field)
            at Bond.Expressions.ObjectParser.<>c__DisplayClassc.<Apply>b__7(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField)
            at System.Linq.Enumerable.<SelectManyIterator>d__4`3.MoveNext()
            at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
            at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
            at Bond.Expressions.ObjectParser.Apply(ITransform transform)
            at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase)
            at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass2.<GenerateSerialize>b__0(IParser p)
            at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline)
            at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.Value(IParser parser, Expression valueType, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.<>c__DisplayClassc.<>c__DisplayClasse.<Struct>b__7(IParser fieldParser, Expression fieldType)
            at Bond.Expressions.Field.Bond.Expressions.IField.Value(IParser parser, Expression valueType)
            at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field)
            at Bond.Expressions.ObjectParser.<>c__DisplayClassc.<Apply>b__7(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField)
            at System.Linq.Enumerable.<SelectManyIterator>d__4`3.MoveNext()
            at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
            at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
            at Bond.Expressions.ObjectParser.Apply(ITransform transform)
            at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase)
            at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass2.<GenerateSerialize>b__0(IParser p)
            at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline)
            at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.Generate(IParser parser)
            at Bond.Serializer`1..ctor(Type type)
            at Bond.Serialize.Cache`2..cctor()
       InnerException:

**Comment by sapek** [comment]
Multiple aliases are definitely supported, e.g. [see](https://github.com/Microsoft/bond/blob/9634ef5a8ba61e874fb0057d29e9c1201e03028b/cs/test/core/Aliases.bond#L3-L8) [the](https://github.com/Microsoft/bond/blob/9634ef5a8ba61e874fb0057d29e9c1201e03028b/cs/test/core/TypeAliasTests.cs#L9-L37) [tests](https://github.com/Microsoft/bond/blob/9634ef5a8ba61e874fb0057d29e9c1201e03028b/cs/test/core/Core.csproj#L53).

If you post link to your project I can take a look what might be the problem.

**Comment by sapek** [comment]
Since there are unit tests with multiple type aliases I suspect that this is not the problem so I'm closing this issue. Please open an issue with more specific information (ideally a repro).
