### ISSUE TITLE
CompactBinary Protocol V2 doesn't work in C#

### ISSUE THREAD

**Issue by kylemc** [Microsoft/bond#70]
I updated the Serialization sample to use CBV2 and now it throws a runtime exception. I've seen similar errors with other IDL, but it appears there's some amount of corruption going on with V2.

Code (program.cs):

    var writer = new CompactBinaryWriter<OutputBuffer>(output, 2 /* used to be 1 */);

    // The first calls to Serialize.To and Deserialize<T>.From can take
    // a relatively long time because they generate the de/serializer 
    // for a given type and protocol.
    Serialize.To(writer, src);

    var input = new InputBuffer(output.Data);
    var reader = new CompactBinaryReader<InputBuffer>(input, 2 /* used to be 1 */);

Exception:

> System.IO.InvalidDataException was unhandled
  HResult=-2146233087
  Message=Invalid type BT_UINT64, expected BT_STRING
  Source=Bond
  StackTrace:
       at Bond.Expressions.ThrowExpression.ThrowInvalidTypeException(BondDataType expectedType, BondDataType actualType)
       at lambda_method(Closure , CompactBinaryReader`1 )
       at Bond.Deserializer`1.Deserialize[T](R reader)
       at Bond.Deserialize`1.From[R](R reader)
       at Examples.Program.Main() in c:\Users\kylemc\Documents\Visual Studio 2013\Projects\serialization\program.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by sapek** [comment]
Yes, CBv2 writer is not support in C# at the moment. Reader is supported.

**Comment by kylemc** [comment]
When do you think the CBv2 writer will be supported?

**Comment by sapek** [comment]
I don't have a specific date at the moment.

For context, what makes CBv2 different from other protocols is that is requires double pass during serialization in order to calculate lengths of nested structs. That's why it requires some additional infrastructure that other protocols don't. That is also why not that many people have been using it (the double pass is an extra cost) so it hasn't been on top of the priority list.
