### ISSUE TITLE
Need better errors/diagnostics when a type that can't be de/serialized is encountered

### ISSUE THREAD

**Issue by kylemc** [Microsoft/bond#80]
This is a re-raising of issue #68 with a better repro. When I update the guid example with the following IDL, I get a TypeInitializationException.

schema.bond
```
import "bond/core/bond.bond"

namespace Examples

using guid = bond.GUID;

struct Example
{
    0: guid id;
}
```

program.cs
```
public static class BondTypeAliasConverter
{
    public static Guid Convert(GUID value, Guid unused)
    {
        return default(Guid);
    }

    public static GUID Convert(Guid value, GUID unused)
    {
        return default(GUID);
    }
}
```

```
System.TypeInitializationException was unhandled
  HResult=-2146233036
  Message=The type initializer for 'Cache`2' threw an exception.
  Source=Bond
  TypeName=Cache`2
  StackTrace:
       at Bond.Serialize.To[W,T](W writer, T obj)
       at Examples.Program.Main() in C:\Users\kylemc\Desktop\ToSave\ToSave\guid\program.cs:line 34
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2147467261
       Message=Value cannot be null.
Parameter name: field
       ParamName=field
       Source=System.Core
       StackTrace:
            at System.Linq.Expressions.Expression.Field(Expression expression, FieldInfo field)
            at Bond.Expressions.DataExpression.PropertyOrField(Expression expression, String name)
            at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field)
            at Bond.Expressions.ObjectParser.<>c__DisplayClassc.<Apply>b__7(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField)
            at System.Linq.Enumerable.<SelectManyIterator>d__4`3.MoveNext()
            at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
            at Bond.Expressions.ObjectParser.Apply(ITransform transform)
            at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase)
            at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass2.<GenerateSerialize>b__0(IParser p)
            at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline)
            at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.Value(IParser parser, Expression valueType, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.<>c__DisplayClassc.<>c__DisplayClasse.<Struct>b__7(IParser fieldParser, Expression fieldType)
            at Bond.Expressions.Field.Bond.Expressions.IField.Value(IParser parser, Expression valueType)
            at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field)
            at Bond.Expressions.ObjectParser.<>c__DisplayClassc.<Apply>b__7(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField)
            at System.Linq.Enumerable.<SelectManyIterator>d__4`3.MoveNext()
            at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
            at Bond.Expressions.ObjectParser.Apply(ITransform transform)
            at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase)
            at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass2.<GenerateSerialize>b__0(IParser p)
            at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline)
            at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema)
            at Bond.Expressions.SerializerTransform`2.Generate(IParser parser)
            at Bond.Serializer`1..ctor(Type type)
            at Bond.Serialize.Cache`2..cctor()
       InnerException: 
```

**Comment by sapek** [comment]
As explained in the [documentation](https://microsoft.github.io/bond/manual/bond_cs.html#converter) the converter applies to aliases of scalars, strings and blobs. `bond.GUID` is a Bond defined struct.

**Comment by kylemc** [comment]
It seems pretty aggressive to close this issue so fast.

1) It would be better if there were an explicit compile time or runtime failure. It was very difficult to track down the root cause of this failure.

2) Why not expand support to structs? It seems like this could be considered an "enhancement" request instead of being closed outright.

**Comment by sapek** [comment]
1 is a fair point but that should be a different issue with an appropriate title. BTW, alias `using guid = bond.GUID` is perfectly fine. What is not fine is mapping such an alias to a type (`System.DateTime` in your case) that is not Bond serializable (i.e. is not annotated with `[Bond.Schema]`). We will not support copying from one object to another (which is what `BondTypeAliasConverter` does) to support such mapping. If we wanted to support serializing classes/structs that are not annotated with Bond attributes we would take a different approach (user defined reflection provider) that doesn't require a copy during de/serialization.

**Comment by kylemc** [comment]
If I just change the title on this one can you repurpose it for 1 (I'm not sure if it's possible to re-open these)?

I think I follow what you're saying for 2. Feel free to put the scenario on the backlog. System.Guid is definitely the most useful representation of a Guid. My only real option with the current features is to map it to a "string", right?

**Comment by sapek** [comment]
`string` or `blob`, depending if you care about small binary representation or human readable text representation.

**Comment by kylemc** [comment]
Great. Thanks.

**Comment by goodvinj** [comment]
What's the state of the issue?
I return result from the service via "Message.From(...)" and a single place where I see the exception out of the serialization is a GRPC console log.
So I get no exceptions on the server side.
