### ISSUE TITLE
[C#] .NET Core Deserialize

### ISSUE THREAD

**Issue by RohanNagar** [Microsoft/bond#837]
Hi,

I am trying to deserialize a binary bond file in .NET Core. Can someone help me figure out what I'm doing wrong? I don't really know where to start. I am getting this error:

```
Unhandled Exception: System.IO.InvalidDataException: Invalid BondDataType 20
   at Bond.Protocols.Throw.InvalidBondDataType(BondDataType type) in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\protocols\Exceptions.cs:line 14
   at Bond.Protocols.CompactBinaryReader`1.Skip(BondDataType type) in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\protocols\CompactBinary.cs:line 856
   at Bond.Protocols.CompactBinaryReader`1.SkipStruct() in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\protocols\CompactBinary.cs:line 922
   at Bond.Protocols.CompactBinaryReader`1.Skip(BondDataType type) in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\protocols\CompactBinary.cs:line 853
   at lambda_method(Closure , CompactBinaryReader`1 )
   at Bond.Deserializer`1.Deserialize[T](R reader) in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\Deserializer.cs:line 219
   at Bond.Deserialize`1.From[R](R reader) in C:\Users\edus\azure\rel\Bonding-NuGet\bond\cs\src\core\Deserializer.cs:line 43
```

My code:

```cs
using (FileStream bundle = File.OpenRead(path))
{
    var byteArray = ReadStreamToByteArray(bundle);

    var inputBuffer = new InputBuffer(byteArray, byteArray.Length);
    var reader = new CompactBinaryReader<InputBuffer>(inputBuffer);
    var bundleObject = Deserialize<T>.From(reader);

    return bundleObject;
}
```

If I change the `InputBuffer` to `InputStream` and the `CompactBinaryReader` to `FastBinaryReader`, then it works fine on Windows. But, since those classes are in the `Bond.IO.Unsafe` namespace, the same code does not work on Linux. I need to use the `Bond.IO.Safe` namespace, and `InputBuffer` is the only way to read in that namespace.

Any ideas?

**Comment by chwarr** [comment]
Compact Binary and Fast Binary are different encoding protocols and are not mutually compatible with each other. (E.g., they represent integers differently.)

If your payload is Fast Binary, you must use the `FastBinaryReader`, but you can use it with an `InputBuffer`.

**Comment by RohanNagar** [comment]
I can't believe I didn't even try that @chwarr. Thanks so much, that fixes my problem!
