### ISSUE TITLE
[c#] using alias to map struct not supported?

### ISSUE THREAD

**Issue by redoz** [Microsoft/bond#926]
I was trying to use an alias and a ```--using``` directive to map ```bond.GUID``` into ```System.Guid``` (as an example, I realized ```bond.GUID``` has implicit casts to/from ```System.Guid```).

```test.bond```:
```
using guid = bond.GUID;
struct test {
   0: guid identifier;
}
```
gbc invoked with ```--using="Guid=System.Guid"``` generates the Type the way I would expect it to:
```
...
  [global::Bond.Id(0), global::Bond.Type(typeof(global::Bond.GUID))]
   public System.Guid identifier { get; set; }
...
```
And I've added the appropriate ```BondTypeAliasConverter```.

But it seems I get an exception when trying to construct the serializer,  is this not a supported use-case? 

It looks like it ends up looking for the properties of ```bond.GUID``` on an instance of ```System.Guid``` which results in the following exception:
```

System.TypeInitializationException : The type initializer for 'Cache`2' threw an exception.
  ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.ArgumentNullException : Value cannot be null.
Parameter name: field
   at Bond.Serialize.To[W,T](W writer, T obj) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 33
   at UnitTest.Util.SerializeCB[T](T obj, Stream stream) in C:\dev\vendor\bond\cs\test\core\Util.cs:line 259
   at UnitTest.Util.<>c__DisplayClass98_0`2.<AllSerializeDeserialize>b__3(Action`2 serialize, Func`2 deserialize) in C:\dev\vendor\bond\cs\test\core\Util.cs:line 877
   at UnitTest.Util.AllSerializeDeserialize[From,To](From from, Boolean noTranscoding) in C:\dev\vendor\bond\cs\test\core\Util.cs:line 919
   at UnitTest.SerializationTests.TestSerialization[From,To](Boolean noTranscoding) in C:\dev\vendor\bond\cs\test\core\SerializationTests.cs:line 476
   at UnitTest.SerializationTests.TestSerialization[T](Boolean noTranscoding) in C:\dev\vendor\bond\cs\test\core\SerializationTests.cs:line 484
   at UnitTest.SerializationTests.MyType() in C:\dev\vendor\bond\cs\test\core\SerializationTests.cs:line 269
--TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Bond.Serializer`1..ctor(Type type, IParser parser, Boolean inlineNested) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 117
   at Bond.Serializer`1..ctor(Type type) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 91
   at Bond.Serialize.Cache`2..cctor() in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 21
--ArgumentNullException
   at System.Linq.Expressions.Expression.Field(Expression expression, FieldInfo field)
   at Bond.Expressions.DataExpression.PropertyOrField(Expression expression, String name) in C:\dev\vendor\bond\cs\src\core\expressions\DataExpression.cs:line 16
   at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 102
   at Bond.Expressions.ObjectParser.<>c__DisplayClass21_0.<Apply>b__4(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 88
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Bond.Expressions.ObjectParser.Apply(ITransform transform) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 84
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 173
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 165
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass12_0.<GenerateSerialize>b__0(IParser p) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 146
   at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 59
   at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 155
   at Bond.Expressions.SerializerTransform`2.Value(IParser parser, Expression valueType, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 334
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass15_1.<Struct>b__6(IParser fieldParser, Expression fieldType) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 181
   at Bond.Expressions.Field.Bond.Expressions.IField.Value(IParser parser, Expression valueType) in C:\dev\vendor\bond\cs\src\core\expressions\Transform.cs:line 38
   at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 125
   at Bond.Expressions.ObjectParser.<>c__DisplayClass21_0.<Apply>b__4(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 88
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Bond.Expressions.ObjectParser.Apply(ITransform transform) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 84
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 173
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 165
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass12_0.<GenerateSerialize>b__0(IParser p) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 146
   at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 77
   at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 155
   at Bond.Expressions.SerializerTransform`2.Generate(IParser parser) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 125
   at Bond.Serializer`1.SerializerHelper..ctor(ObjectParser parser, Type type, Boolean inlineNested) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 140
   at Bond.Serializer`1.TwoPassSerializerHelper`1..ctor(ObjectParser parser, Type type, Boolean inlineNested) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 157
```

**Comment by lalo** [comment]
It is not supported, you can only convert scalars, blobs, and strings. I just realized that documentation does not specify this, but as a reference this other issue https://github.com/Microsoft/bond/issues/595

**Comment by redoz** [comment]
Yeah I've been digging through the source code and I found the guid example, I even tried to see if I could add the support myself, but it wasn't trivial, at least not without better understanding of the code-base.

Do you know if that's something you're planning on supporting? I realize it doesn't add capabilities to Bond itself, but it does mean you could create a nicer API surface for generated bond clients/services.

**Comment by lalo** [comment]
What exactly are you trying to solve? There might be alternatives solutions to the problem. I'm guessing it is not related to System.Guid and it is something more complicated since that is pretty much covered.

**Comment by redoz** [comment]
I'm trying to re-use an existing .Net type in the client/service rather than having to use the generated one. But I can of course use a partial to extend the generated type (either with implicit/explicit casts, or with the required functionality).

The type itself is nothing special, it's a generic type of T containing T, and a bool indicating whether it has a value. It exists because I need to be able to distinguish between "the value is null" and "there is no value".

I saw something about custom bonded implementations, but I haven't looked at it yet so I'm not sure if that's something that would be relevant for this?

**Comment by lalo** [comment]
To avoid using a bool, Bond has nullable type: https://microsoft.github.io/bond/manual/bond_cs.html#nullable-types

I'm quite sure you would have to use the generated one since that is what drives the serialization/deserialization. So it has to be represented in terms of a Bond type. For example you can dump it all in a blob but you would have to pay for converting it to your other type by extending the partial class. Also since it's generic you would also have to keep track of what the type is since if you use a blob it won't be smart about it.

I don't think custom bonded implementation will help, but I'll double check.

**Comment by redoz** [comment]
Yeah I'm familiar with the nullable type. 
```
struct bar {
  0: ... // lots of interesting fields here
}
struct foo {
 0: bar something;
}
```
My understanding that in the above case, `something` cannot be null, so I can do:
```
struct foo {
 0: nullable<bar> something;
}
```
And now `something` can also take `null` as a value. 
But I need to be able to have a third option of "there is no value".
So I'd need `nullable<nullable<bar>>` but I don't think that does anything useful (I haven't checked).

One thought was to make
```
struct maybe<T> {
  0: nullable<T> value;
}

struct foo {
  0: nullable<maybe<foo>> something;
}
```
Because I think that would make `something` either:
1. null, indicating no value
2. not null, but `maybe.value` would be null, indicating null is the value
3. not null, and `maybe.value` also not null, indicating a value of type `foo`

But I haven't verified that it works yet.

And yes, I understand that bond will still ship the bond type across the wire (and I don't want to serialize things to blobs because that's what I'm using bond for), so being able to re-use existing types would only serve as a facade, where the alias type converter would convert between the bond and the alias type.

In a somewhat unrelated thought, could it be beneficial (in some instances) to allow `gbc` to produce .Net structs instead of classes?

**Comment by chwarr** [comment]
This appears to have been answered. I'm going to close this issue. Please feel free to re-open if needed.
