### ISSUE TITLE
Is the type alias converter in conjunction with generic fields not supported?

### ISSUE THREAD

**Issue by redoz** [Microsoft/bond#928]
I've modified the `schema.bond` from the `example/cs/core/date_time`  project to include a generic like so:
```
namespace Examples

using DateTime = int64;

struct Wrapper<T> {
    0: T Value;
}

struct Example
{
    0: DateTime Now;
    1: vector<DateTime> Dates;
    2: Wrapper<DateTime> Date;
}
```

But if I try to serialize this I get an exception:
```
System.InvalidOperationException: The binary operator NotEqual is not defined for the types 'System.DateTime' and 'System.Int64'.
   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.NotEqual(Expression left, Expression right)
   at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 169
   at Bond.Expressions.ObjectParser.<>c__DisplayClass21_0.<Apply>b__4(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 88
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Bond.Expressions.ObjectParser.Apply(ITransform transform) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 84
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 173
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 165
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass12_0.<GenerateSerialize>b__0(IParser p) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 146
   at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 59
   at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 155
   at Bond.Expressions.SerializerTransform`2.Value(IParser parser, Expression valueType, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 334
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass15_1.<Struct>b__6(IParser fieldParser, Expression fieldType) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 181
   at Bond.Expressions.Field.Bond.Expressions.IField.Value(IParser parser, Expression valueType) in C:\dev\vendor\bond\cs\src\core\expressions\Transform.cs:line 38
   at Bond.Expressions.ObjectParser.Field(ITransform transform, Expression structVar, UInt16 id, ISchemaField schemaField, IField field) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 125
   at Bond.Expressions.ObjectParser.<>c__DisplayClass21_0.<Apply>b__4(<>f__AnonymousType0`2 <>h__TransparentIdentifier0, IField knownField) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 88
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Bond.Expressions.ObjectParser.Apply(ITransform transform) in C:\dev\vendor\bond\cs\src\core\expressions\ObjectParser.cs:line 84
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema, Boolean isBase) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 173
   at Bond.Expressions.SerializerTransform`2.Struct(IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 165
   at Bond.Expressions.SerializerTransform`2.<>c__DisplayClass12_0.<GenerateSerialize>b__0(IParser p) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 146
   at Bond.Expressions.SerializerGenerator`2.GenerateSerialize(Serialize serialize, IParser parser, ParameterExpression writer, Boolean inline) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 77
   at Bond.Expressions.SerializerTransform`2.GenerateSerialize(SerializeWithSchema serializeWithSchema, IParser parser, RuntimeSchema schema) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 155
   at Bond.Expressions.SerializerTransform`2.Generate(IParser parser) in C:\dev\vendor\bond\cs\src\core\expressions\SerializerTransform.cs:line 125
   at Bond.Serializer`1.SerializerHelper..ctor(ObjectParser parser, Type type, Boolean inlineNested) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 140
   at Bond.Serializer`1.TwoPassSerializerHelper`1..ctor(ObjectParser parser, Type type, Boolean inlineNested) in C:\dev\vendor\bond\cs\src\core\Serializer.cs:line 157
```

Is this not a supported use-case?

**Comment by lalo** [comment]
This will be fixed on the next release, estimate at least 3-4 weeks until it hits nuget. Thanks for reporting.

**Comment by redoz** [comment]
We worked around it for now by adding "required" which avoids the comparison to default.

Thanks for the quick response & fix. Any plans of hosting nightlies in a myget feed or something?

**Comment by lalo** [comment]
That is a good suggestion we have not considered. Thanks for the suggestion :+1:  

We'll see if we have support or cycles to scaffold that.
