### ISSUE TITLE
NotImplementedException when trying to deserialize complex type from json

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/bond#96]
I want to deserialize complex bond. Exception got thrown when I'm using ```SimpleJsonWriter```. Is there some examples on json deserialization of complex types? Here is a schema I'm trying:

``` json
struct InnerStruct
{
    10: optional string baseType;
}
struct Record
{
    0: string Name;
    1: vector<double> Constants;
    2: optional bonded<InnerStruct> data;
}
```

Code:

``` csharp
var src = new Record
{
    Name = "FooBar",
    Constants = { 3.14, 6.28 },
    data = new Bonded<InnerStruct>(new InnerStruct() { baseType = "a" })
};

var jsonString = new StringBuilder();
var jsonWriter = new SimpleJsonWriter(new StringWriter(jsonString));

Serialize.To(jsonWriter, src);
jsonWriter.Flush();

var reader = new SimpleJsonReader(new StringReader(jsonString.ToString()));
src = Deserialize<Record>.From(reader);
```

Output:

```
{"Name":"FooBar","Constants":[3.14,6.28],"data":{"baseType":"a"}}

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Cache`1' threw an exception. ---> System.NotImplementedException: The method or operation is not implemented.
   at Bond.Expressions.Pull.PullParser`1.Bonded(ValueHandler handler)
   at Bond.Expressions.DeserializerTransform`1.Value(IParser parser, Expression var, Expression valueType, Type schemaType, Boolean initialize)
   at Bond.Expressions.DeserializerTransform`1.CheckedValue(IParser parser, Expression var, Expression valueType, Type schemaType, Boolean initialize)
   at Bond.Expressions.DeserializerTransform`1.<>c__DisplayClass11.<>c__DisplayClass15.<Struct>b__c(IParser fieldParser, Expression fieldType)
   at Bond.Expressions.Field.Bond.Expressions.IField.Value(IParser parser, Expression valueType)
   at Bond.Expressions.Json.SimpleJsonParser`1.ProcessField(ParameterExpressionrequiredFields, IEnumerable`1 transforms)
   at Bond.Expressions.Json.SimpleJsonParser`1.<>c__DisplayClass9.<CreateStateMachine>b__8(Expression state)
   at Bond.Expressions.Pull.StateTransition.<>c__DisplayClass2.<.ctor>b__0(Expression s)
   at Bond.Expressions.Pull.StateTransition.Bond.Expressions.Pull.IStateTransition.Body(Expression state)
   at Bond.Expressions.Pull.PullParser`1.<>c__DisplayClassc.<CaseForToken>b__a(IStateTransition transition)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Bond.Expressions.Pull.PullParser`1.CaseForToken(ITokenTransition`1 tokenTransition, Expression state)
   at Bond.Expressions.Pull.PullParser`1.<>c__DisplayClass8.<SwitchToken>b__5(ITokenTransition`1 transition)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Bond.Expressions.Pull.PullParser`1.SwitchToken(IStateMachine`1 machine, Expression state)
   at Bond.Expressions.Pull.PullParser`1.Apply(ITransform transform)
   at Bond.Expressions.DeserializerTransform`1.Struct(IParser parser, Expression var, Type schemaType, Boolean initialize)
   at Bond.Expressions.DeserializerTransform`1.Deserialize(IParser parser, Expression var, Type objectType, Type schemaType, Boolean initialize)
   at Bond.Expressions.DeserializerTransform`1.Generate(IParser parser, Type type)
   at Bond.Deserializer`1..ctor(Type type, IParser parser, IFactory factory, Boolean inlineNested)
   at Bond.Deserializer`1..ctor(Type type)
   at Bond.Deserialize`1.Cache`1..cctor()
   --- End of inner exception stack trace ---
   at Bond.Deserialize`1.From[R](R reader)
   at TryBond.Program.Main() in c:\temp\TryBond\TryBond\Program.cs:line 35
```

**Comment by sapek** [comment]
Text protocols like JSON and Xml don't support `bonded<T>`. This is because the implementation uses streaming parsers (for better performance) which can't be cloned. `bonded<T>` has lazy deserialization semantics which means that during deserialization of the containing structure it needs to make a clone of the protocol in order to deserialize from it later. It will work if you change your schema to:
```
struct Record
{
    0: string Name;
    1: vector<double> Constants;
    2: InnerStruct data;
}
```

**Comment by SergeyKanzhelev** [comment]
What I want to achieve is to parse InnerStruct's ```baseType``` field and than apply proper deserializer to it. Is it possible with Json parser?

Schema like this:
```
namespace Examples
struct InnerStruct
{
    10: optional string baseType;
};
struct InnerStruct1: InnerStruct
{
    10: optional string baseType;
	20: string newField1;
};
struct InnerStruct2 : InnerStruct
{
    10: optional string baseType;
	20: string newField2;
};
struct Record
{
    0: string Name;
    1: vector<double> Constants;
    2: optional InnerStruct data;
};
```

**Comment by sapek** [comment]
No, today polymorphism is not supported with JSON or Xml.

**Comment by SergeyKanzhelev** [comment]
Do you have it in plans? Is there a way to implement it using any sort of extensibility bond provides?

**Comment by sapek** [comment]
We intend to support it but we are still investigating what the best approach is. 

One option, which could be implemented using Bond extensibility mechanisms, is to implement JSON protocol using a DOM parser. This would require a new parser functionally equivalent to `SimpleJsonParser` (although probably simpler because stream parsing it more difficult). This is how polymorphism works with JSON in the C++ implementation.

**Comment by SergeyKanzhelev** [comment]
@abaranch for information. 

@sapek we need a tool to parse [Application Insights](https://github.com/Microsoft/ApplicationInsights-dotnet) events which are bond-schema JSON in our tests. We are using custom tool to generate those parsers, but would really like to use something official, at least for functional tests.

**Comment by wasker** [comment]
That be very nice to have this addressed.

**Comment by chandramouleswaran** [comment]
I have been trying to make IBonded work with Newtonsoft JSON serializer.

One way to solve this problem is (not a clean solution though)
1. Enable TypeNameHandling on the Json settings to all
2. Expose the instance from Bonded class. I had to write a decorator to do this.

Is there a reason why the instance is not exposed in the Bonded class? What hard could that cause?

**Comment by alexmg** [comment]
:+1: Agreed. It would be nice to see this implemented.
